version: 2.1
orbs:
  newman: postman/newman@0.0.2
workflows:
  commit:
    jobs:
      - newman-collection-run
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./postman/collection.json
